#ifndef DEFINES_H_78JFYUBT
#define DEFINES_H_78JFYUBT

#define FIRMWARE_VERSION "0.1"
#define DEVICE_NAME "Pure C Arduino Logic Sniffer v" 

#define SERIAL_SPEED E_BAUD_115200
#define DEVICE_PROBES 6
#define DEVICE_STATIC_SAMPLES 512
#define DEVICE_DYNAMIC_SAMPLES 0
#define DEVICE_SAMPLE_RATE 1000000

#define DEBUG_ENABLED 0

#endif /* end of include guard: DEFINES_H_78JFYUBT */

